name: ci-docs-workflow
run-name: Generating docs for ${{ github.ref }}
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm i

      - name: Generate docs
        run: npx oclif readme

      - name: Commit docs
        env:
          HEAD_REF: ${{ github.event.workflow_run.head_branch }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Generate docs: ${{ github.ref }}"
          git push origin HEAD:$HEAD_REF
